// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCadO7RPpTM5_dsTkPOo4ZlxV2BWJGtqJc',
    appId: '1:911331160892:web:b650aab84acf3fa8c42439',
    messagingSenderId: '911331160892',
    projectId: 'aplicatiemedicala-b65c8',
    authDomain: 'aplicatiemedicala-b65c8.firebaseapp.com',
    storageBucket: 'aplicatiemedicala-b65c8.appspot.com',
    measurementId: 'G-4FDV1BET8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf-22i8emSRfd7INAvu4FHLePJUPcZZ4s',
    appId: '1:911331160892:android:1d480954626c4423c42439',
    messagingSenderId: '911331160892',
    projectId: 'aplicatiemedicala-b65c8',
    storageBucket: 'aplicatiemedicala-b65c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqr6a2RDhPIYSbVqXdTfjsn-pD2tAuSVQ',
    appId: '1:911331160892:ios:dd24f013b51396b9c42439',
    messagingSenderId: '911331160892',
    projectId: 'aplicatiemedicala-b65c8',
    storageBucket: 'aplicatiemedicala-b65c8.appspot.com',
    iosBundleId: 'com.example.proiectMonitoorizarePacienti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqr6a2RDhPIYSbVqXdTfjsn-pD2tAuSVQ',
    appId: '1:911331160892:ios:727b3a5bdbbeab71c42439',
    messagingSenderId: '911331160892',
    projectId: 'aplicatiemedicala-b65c8',
    storageBucket: 'aplicatiemedicala-b65c8.appspot.com',
    iosBundleId: 'com.example.proiectMonitoorizarePacienti.RunnerTests',
  );
}
